language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - wget https://getcomposer.org/composer.phar
  - php composer.phar install --no-interaction
  - composer self-update
  - git clone https://github.com/octobercms/october.git
  - mkdir -p ./october/plugins/vuetober/rainlabuserapi
  - mv !(october) october/plugins/vuetober/rainlabuserapi
  - cd october
  - composer install
  - cp config/cms.php config/testing/cms.php
  - cd plugins/vuetober/rainlabuserapi

script:
  - php vendor/bin/phpunit